plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
  - linearity.md

theme: jekyll-theme-tactile

markdown: kramdown
kramdown:
  parse_block_html: true

navigation:
  - text: 1. Linearity
    internal: true
    url: ./linearity
  - text: 2. Order Reduction
    internal: true
    url: ./orderreduction   
  - text: 3. Solvability
    internal: true
    url: ./solvability
  - text: 4. Stability
    url: ./stability